FROM osgeo/gdal:ubuntu-full-3.3.2

RUN apt-get update -y \
    && apt-get install -y language-pack-en language-pack-zh-hans \
    && locale-gen en_US.UTF-8 \
    && locale-gen zh_CN.UTF-8 \
    && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
		&& apt-get clean -y

ENV LANG=zh_CN.UTF-8 LANGUAGE=zh_CN:zh LC_ALL=zh_CN.UTF-8