apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: change-detection-new-download
  namespace: default
spec:
  entrypoint: change-detection-new-download
  arguments:
    parameters:
      - name: ceph_path
        value: /mnt/cephfs
      - name: share_path
        value: /mnt/cifs
      - name: exec_code
        value: RSI202011091504
      - name: tenant_id
        value: 1
      - name: input_bucket
        value: rsi-private-beta
      - name: output_bucket
        value: rsi-operator
      - name: accesskey
        value: EY10QIYRK26F4CL0EY60
      - name: secretkey
        value: noYU7VQHMCojxX8ziuF04bAOMBUhKUKr79FcwyOQ
      - name: endpoint
        value: '10.4.1.110:7480'
      - name: inner_endpoint
        value: '10.4.1.110:7480'
      - name: protocol
        value: http
      - name: inner_protocol
        value: http
      - name: store_type
        value: 2
      - name: env
        value: beta5
      - name: input_front_file
        value: /mnt/cephfs/rsi/data/Test/mlm/cd/P_GZ_test15_2005_0101_Level_18.tif
      - name: front_file_name
        value: P_GZ_test15_2005_0101_Level_18
      - name: input_back_file
        value: /mnt/cephfs/rsi/data/Test/mlm/cd/P_GZ_test15_2015_0202_Level_18.tif
      - name: change_type
        value: nature_artificial
  onExit: ''
  templates:
    - name: change-detection-new-download
      parallelism: 150
      inputs:
        parameters:
          - name: ceph_path
          - name: share_path
          - name: exec_code
          - name: tenant_id
          - name: input_bucket
          - name: output_bucket
          - name: accesskey
          - name: secretkey
          - name: endpoint
          - name: inner_endpoint
          - name: protocol
          - name: inner_protocol
          - name: store_type
          - name: env
          - name: input_front_file
          - name: front_file_name
          - name: input_back_file
          - name: change_type
        artifacts: []
      dag:
        tasks:
          - name: segmentation-changes-npqj
            template: topo-1653702930309
            key: topo-1653702930309
            arguments:
              parameters:
                - name: task
                  value: '1'
                - name: inputADir
                  value: '{{inputs.parameters.input_front_file}}'
                - name: fileName
                  value: '{{inputs.parameters.front_file_name}}'
                - name: outputDir
                  value: >-
                    {{inputs.parameters.ceph_path}}/rsi/result/{{inputs.parameters.tenant_id}}/{{inputs.parameters.exec_code}}/change_detection
                - name: typeChange
                  value: '{{inputs.parameters.change_type}}'
                - name: inputBDir
                  value: '{{inputs.parameters.input_back_file}}'
                - name: operatorCode
                  value: upgradeChangeCompress
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
            dependencies: []
      outputs:
        parameters: []
        artifacts: []
    - name: delay
      inputs:
        parameters:
          - name: time
      suspend:
        duration: '{{inputs.parameters.time}}'
    - name: topo-1653702930309
      inputs:
        parameters:
          - name: task
          - name: inputADir
          - name: fileName
          - name: outputDir
          - name: typeChange
          - name: inputBDir
          - name: operatorCode
          - name: tenantId
          - name: execCode
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-segmentation:v0.8.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 8
          requests:
            memory: 8Gi
            cpu: 8
        args: 
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --task={{inputs.parameters.task}}
            --inputADir={{inputs.parameters.inputADir}}
            --fileName={{inputs.parameters.fileName}}
            --outputDir={{inputs.parameters.outputDir}}
            --typeChange={{inputs.parameters.typeChange}}
            --inputBDir={{inputs.parameters.inputBDir}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --spring.config.location={{workflow.parameters.ceph_path}}/rsi/config/application-{{workflow.parameters.env}}.yml
            --s3.protocol={{workflow.parameters.protocol}}
            --s3.ak={{workflow.parameters.accesskey}}
            --s3.sk={{workflow.parameters.secretkey}}
            --s3.bucket={{workflow.parameters.output_bucket}}
            --s3.endpoint={{workflow.parameters.endpoint}}
            --s3.lanEndpoint={{workflow.parameters.inner_endpoint}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
          - name: uploaddir
            mountPath: /mnt/cephfs/rsi-private-beta/rsi
  volumes:
    - name: workdir
      hostPath:
        path: '{{workflow.parameters.ceph_path}}'
    - name: sharedir
      hostPath:
        path: '{{workflow.parameters.share_path}}'
    - name: uploaddir
      hostPath:
        path: /mnt/cephfs/rsi-private-beta/rsi
    - name: cache
      emptyDir:
        medium: Memory
        sizeLimit: 65536Mi
