apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: create-pyammid
  namespace: default
spec:
  entrypoint: create-pyammid
  arguments:
    parameters:
      - name: ceph_path
        value: /mnt/cephfs
      - name: share_path
        value: /mnt/cifs
      - name: exec_code
        value: RSI202012345678
      - name: tenant_id
        value: 1
      - name: input_bucket
        value: rsi-operator-dev113
      - name: output_bucket
        value: rsi-operator-dev113
      - name: accesskey
        value: HBE4ZPQA3OLNNSMUNWWC
      - name: secretkey
        value: NNdgyDR3LbdpnmXe8APcHlnkTnbFOND2bs9lCmyU
      - name: endpoint
        value: 'oss-dev1.e-tudou.com:7480'
      - name: inner_endpoint
        value: 'oss-dev1.e-tudou.com:7480'
      - name: protocol
        value: http
      - name: inner_protocol
        value: http
      - name: store_type
        value: 2
      - name: env
        value: dev1
      - name: img_list
        value: |
          [{"inputFile":"/mnt/cephfs/rsi113/original/雁塔数据/GF2_PMS1_E108.9_N34.2_20181026_L1A0003549596/GF2_PMS1_E108.9_N34.2_20181026_L1A0003549596-MSS1.tiff"},{"inputFile":"/mnt/cephfs/rsi113/original/雁塔数据/GF2_PMS1_E108.9_N34.2_20181026_L1A0003549596/GF2_PMS1_E108.9_N34.2_20181026_L1A0003549596-PAN1.tiff"},{"inputFile":"/mnt/cephfs/rsi113/original/雁塔数据/GF2_PMS2_E109.1_N34.2_20181026_L1A0003549601/GF2_PMS2_E109.1_N34.2_20181026_L1A0003549601-MSS2.tiff"},{"inputFile":"/mnt/cephfs/rsi113/original/雁塔数据/GF2_PMS2_E109.1_N34.2_20181026_L1A0003549601/GF2_PMS2_E109.1_N34.2_20181026_L1A0003549601-PAN2.tiff"}]
  onExit: ''
  templates:
    - name: create-pyammid
      parallelism: 150
      inputs:
        parameters:
          - name: ceph_path
          - name: share_path
          - name: exec_code
          - name: tenant_id
          - name: input_bucket
          - name: output_bucket
          - name: accesskey
          - name: secretkey
          - name: endpoint
          - name: inner_endpoint
          - name: protocol
          - name: inner_protocol
          - name: store_type
          - name: env
          - name: img_list
        artifacts: []
      dag:
        tasks:
          - name: create-pyamid-iksk
            template: topo-1602310517387
            key: topo-1602310517387
            arguments:
              parameters:
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: createPyammid
                - name: inputImageFilePath
                  value: '{{item.inputFile}}'
                - name: resampleMethod
                  value: AVERAGE
            dependencies: []
            withParam: '{{inputs.parameters.img_list}}'
      outputs:
        parameters: []
        artifacts: []
    - name: delay
      inputs:
        parameters:
          - name: time
      suspend:
        duration: '{{inputs.parameters.time}}'
    - name: topo-1602310517387
      inputs:
        parameters:
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: inputImageFilePath
          - name: resampleMethod
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-xq:v0.12.0'
        command:
          - sh
          - '-c'
        securityContext:
          privileged: true
        imagePullPolicy: Always
        args:
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --inputImageFilePath={{inputs.parameters.inputImageFilePath}}
            --resampleMethod={{inputs.parameters.resampleMethod}}
            --spring.config.location={{workflow.parameters.ceph_path}}/rsi/config/application-{{workflow.parameters.env}}.yml
            --s3.protocol={{workflow.parameters.protocol}}
            --s3.ak={{workflow.parameters.accesskey}}
            --s3.sk={{workflow.parameters.secretkey}}
            --s3.bucket={{workflow.parameters.output_bucket}}
            --s3.endpoint={{workflow.parameters.endpoint}}
            --s3.lanEndpoint={{workflow.parameters.inner_endpoint}}
        resources:
          limits:
            memory: 8Gi
            cpu: 2
          requests:
            memory: 8Gi
            cpu: 2
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
          - name: uploaddir
            mountPath: /mnt/cephfs/rsi-private-beta/rsi
  hostNetwork: true
  volumes:
    - name: workdir
      hostPath:
        path: '{{workflow.parameters.ceph_path}}'
    - name: sharedir
      hostPath:
        path: '{{workflow.parameters.share_path}}'
    - name: uploaddir
      hostPath:
        path: /mnt/cephfs/rsi-private-beta/rsi
