apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dehaze-batch
  namespace: default
spec:
  entrypoint: dehaze-batch
  arguments:
    parameters:
      - name: ceph_path
        value: /mnt/cephfs/rsi-data
      - name: share_path
        value: /mnt/cifs
      - name: exec_code
        value: RSI202012111412
      - name: tenant_id
        value: 1
      - name: input_bucket
        value: rsi-private-beta5
      - name: output_bucket
        value: rsi-private-beta5
      - name: accesskey
        value: HBE4ZPQA3OLNNSMUNWWC
      - name: secretkey
        value: NNdgyDR3LbdpnmXe8APcHlnkTnbFOND2bs9lCmyU
      - name: endpoint
        value: '192.168.0.41:7480'
      - name: inner_endpoint
        value: '192.168.0.41:7480'
      - name: protocol
        value: http
      - name: inner_protocol
        value: http
      - name: store_type
        value: 2
      - name: env
        value: private
      - name: input_path
        value: /mnt/cephfs/rsi-data/result/1/RSI202205051/DOM/dodging
      - name: output_path
        value: /mnt/cephfs/rsi-data/result/1/RSI202205051/DOM
      - name: domega
        value: 0.95
      - name: dehaze_method
        value: 0
      - name: exposure_suppress
        value: 0
      - name: b_clahe
        value: 'false'
      - name: d_cut_limit
        value: 1
      - name: all_band_clahe
        value: 0
  onExit: ''
  templates:
    - name: dehaze-batch
      parallelism: 150
      inputs:
        parameters:
          - name: ceph_path
          - name: share_path
          - name: exec_code
          - name: tenant_id
          - name: input_bucket
          - name: output_bucket
          - name: accesskey
          - name: secretkey
          - name: endpoint
          - name: inner_endpoint
          - name: protocol
          - name: inner_protocol
          - name: store_type
          - name: env
          - name: input_path
          - name: output_path
          - name: domega
          - name: dehaze_method
          - name: exposure_suppress
          - name: b_clahe
          - name: d_cut_limit
          - name: all_band_clahe
        artifacts: []
      dag:
        tasks:
          - name: xq-batch-rule-8235
            template: topo-1634981028628
            key: topo-1634981028628
            arguments:
              parameters:
                - name: result_dir
                  value: '{{inputs.parameters.output_path}}'
                - name: input_dir
                  value: '{{inputs.parameters.input_path}}'
                - name: output_file
                  value: /tmp/image_parallel.json
                - name: suffix
                  value: .tif
            dependencies: []
          - name: xq-dehaze-uzwn
            template: topo-1640051672030
            key: topo-1640051672030
            arguments:
              parameters:
                - name: input_file
                  value: >-
                    `cat /tmp/image_parallel.json | jq
                    '.[{{item}}].input_file'| sed 's/\"//g'`
                - name: output_file
                  value: >-
                    `cat /tmp/image_parallel.json | jq
                    '.[{{item}}].dehaze_file'| sed 's/\"//g'`
                - name: config_file
                  value: XQDeHazeCmd.xml
                - name: self_adjust
                  value: 'true'
                - name: n_block_size
                  value: '10'
                - name: n_guide_block_size
                  value: '40'
                - name: n_max_atom
                  value: '240'
                - name: d_epsilon
                  value: '0.001'
                - name: d_sky
                  value: '25'
                - name: d_omega
                  value: '{{inputs.parameters.domega}}'
                - name: dehaze_method
                  value: '{{inputs.parameters.dehaze_method}}'
                - name: b_clahe
                  value: '{{inputs.parameters.b_clahe}}'
                - name: d_cut_limit
                  value: '{{inputs.parameters.d_cut_limit}}'
                - name: all_band_clahe
                  value: '{{inputs.parameters.all_band_clahe}}'
                - name: expose_control
                  value: '{{inputs.parameters.exposure_suppress}}'
              artifacts:
                - name: items
                  from: '{{tasks.xq-batch-rule-8235.outputs.artifacts.items}}'
            dependencies:
              - xq-batch-rule-8235
            withSequence:
              count: '{{tasks.xq-batch-rule-8235.outputs.parameters.count}}'
      outputs:
        parameters: []
        artifacts: []
    - name: delay
      inputs:
        parameters:
          - name: time
      suspend:
        duration: '{{inputs.parameters.time}}'
    - name: topo-1634981028628
      inputs:
        parameters:
          - name: result_dir
          - name: input_dir
          - name: output_file
          - name: suffix
      outputs:
        artifacts:
          - name: items
            path: /tmp/image_parallel.json
        parameters:
          - name: count
            valueFrom:
              path: /tmp/count
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-parallel:v0304'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: 
          - >-
            python3 /opt/rsi/process/xq_batch_rule_multi_source.py
            --result_dir={{inputs.parameters.result_dir}}
            --input_dir={{inputs.parameters.input_dir}}
            --output_file={{inputs.parameters.output_file}}
            --suffix={{inputs.parameters.suffix}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
          - name: uploaddir
            mountPath: /mnt/cephfs/rsi-private-beta/rsi
    - name: topo-1640051672030
      inputs:
        parameters:
          - name: input_file
          - name: output_file
          - name: config_file
          - name: self_adjust
          - name: n_block_size
          - name: n_guide_block_size
          - name: n_max_atom
          - name: d_epsilon
          - name: d_sky
          - name: d_omega
          - name: dehaze_method
          - name: b_clahe
          - name: d_cut_limit
          - name: all_band_clahe
          - name: expose_control
        artifacts:
          - name: items
            path: /tmp/image_parallel.json
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-xq:v0.12.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: 
          - >-
            python3 /opt/rsi/xq_dehaze_cmd.py
            --input_file={{inputs.parameters.input_file}}
            --output_file={{inputs.parameters.output_file}}
            --config_file={{inputs.parameters.config_file}}
            --self_adjust={{inputs.parameters.self_adjust}}
            --n_block_size={{inputs.parameters.n_block_size}}
            --n_guide_block_size={{inputs.parameters.n_guide_block_size}}
            --n_max_atom={{inputs.parameters.n_max_atom}}
            --d_epsilon={{inputs.parameters.d_epsilon}}
            --d_sky={{inputs.parameters.d_sky}}
            --d_omega={{inputs.parameters.d_omega}}
            --dehaze_method={{inputs.parameters.dehaze_method}}
            --b_clahe={{inputs.parameters.b_clahe}}
            --d_cut_limit={{inputs.parameters.d_cut_limit}}
            --all_band_clahe={{inputs.parameters.all_band_clahe}}
            --expose_control={{inputs.parameters.expose_control}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
          - name: uploaddir
            mountPath: /mnt/cephfs/rsi-private-beta/rsi
  hostNetwork: true
  volumes:
    - name: workdir
      hostPath:
        path: '{{workflow.parameters.ceph_path}}'
    - name: sharedir
      hostPath:
        path: '{{workflow.parameters.share_path}}'
    - name: uploaddir
      hostPath:
        path: /mnt/cephfs/rsi-private-beta/rsi
