apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: export-edit-data-ai
  namespace: default
spec:
  entrypoint: export-edit-data-ai
  arguments:
    parameters:
      - name: ceph_path
        value: /mnt/cephfs/rsi
      - name: share_path
        value: /mnt/cifs
      - name: exec_code
        value: RSI202011091504
      - name: tenant_id
        value: 1
      - name: input_bucket
        value: rsi-private-beta5
      - name: output_bucket
        value: rsi-private-beta5
      - name: accesskey
        value: HBE4ZPQA3OLNNSMUNWWC
      - name: secretkey
        value: NNdgyDR3LbdpnmXe8APcHlnkTnbFOND2bs9lCmyU
      - name: endpoint
        value: '192.168.0.41:7480'
      - name: inner_endpoint
        value: '192.168.0.41:7480'
      - name: protocol
        value: http
      - name: inner_protocol
        value: http
      - name: store_type
        value: 2
      - name: env
        value: beta5
      - name: output_file
        value: /mnt/cephfs/rsi/result.zip
      - name: dataset_id
        value: 1
      - name: version_id
        value: 1
      - name: shp_file
        value: /mnt/cephfs/rsi/in.shp
      - name: obs_dirs_up
        value: /rsi/shapfile/
      - name: xzq_file
        value: /mnt/cephfs/rsi/shapefile/province/province.shp
      - name: xzq_field
        value: PROVINCEC
  onExit: ''
  templates:
    - name: export-edit-data-ai
      parallelism: 150
      inputs:
        parameters:
          - name: ceph_path
          - name: share_path
          - name: exec_code
          - name: tenant_id
          - name: input_bucket
          - name: output_bucket
          - name: accesskey
          - name: secretkey
          - name: endpoint
          - name: inner_endpoint
          - name: protocol
          - name: inner_protocol
          - name: store_type
          - name: env
          - name: output_file
          - name: dataset_id
          - name: version_id
          - name: shp_file
          - name: obs_dirs_up
          - name: xzq_file
          - name: xzq_field
        artifacts: []
      dag:
        tasks:
          - name: ogr2ogr-basic-quys
            template: topo-1635322834720
            key: topo-1635322834720
            arguments:
              parameters:
                - name: input_file
                  value: >-
                    {{inputs.parameters.ceph_path}}/result/{{inputs.parameters.tenant_id}}/{{inputs.parameters.exec_code}}/geojson/edit.json
                - name: output_file
                  value: '{{inputs.parameters.shp_file}}'
            dependencies:
              - geojson-export-ywqk
          - name: geojson-export-ywqk
            template: topo-1635329428266
            key: topo-1635329428266
            arguments:
              parameters:
                - name: dataSetId
                  value: '{{inputs.parameters.dataset_id}}'
                - name: dstPath
                  value: >-
                    {{inputs.parameters.ceph_path}}/result/{{inputs.parameters.tenant_id}}/{{inputs.parameters.exec_code}}/geojson/edit.json
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: exportShpData
                - name: versionId
                  value: '{{inputs.parameters.version_id}}'
            dependencies: []
          - name: compress-us7j
            template: topo-1635329570107
            key: topo-1635329570107
            arguments:
              parameters:
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: compress
                - name: inputFile
                  value: >-
                    {{inputs.parameters.ceph_path}}/result/{{inputs.parameters.tenant_id}}/{{inputs.parameters.exec_code}}/regroup
                - name: outputFile
                  value: '{{inputs.parameters.output_file}}'
                - name: operatorCodeAlias
                  value: edit-compress
            dependencies:
              - center-point-to-shpfile-wqnq
          - name: rsi-upload-jjta
            template: topo-1647571151413
            key: topo-1647571151413
            arguments:
              parameters:
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: uploadFile
                - name: obsDir
                  value: '{{inputs.parameters.obs_dirs_up}}'
                - name: localPath
                  value: '`dirname {{inputs.parameters.shp_file}}`'
                - name: accessKey
                  value: '{{inputs.parameters.accesskey}}'
                - name: secretKey
                  value: '{{inputs.parameters.secretkey}}'
                - name: endpoint
                  value: '{{inputs.parameters.endpoint}}'
                - name: protocol
                  value: '{{inputs.parameters.protocol}}'
                - name: bucket
                  value: '{{inputs.parameters.output_bucket}}'
                - name: operatorCodeAlias
                  value: shapefile-uploadFile
            dependencies:
              - center-point-to-shpfile-wqnq
          - name: center-point-to-shpfile-wqnq
            template: topo-1652175963666
            key: topo-1652175963666
            arguments:
              parameters:
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: createShpByCenterPoint
                - name: inputFile
                  value: '{{inputs.parameters.shp_file}}'
                - name: xzqField
                  value: '{{inputs.parameters.xzq_field}}'
                - name: outputPath
                  value: >-
                    {{inputs.parameters.ceph_path}}/result/{{inputs.parameters.tenant_id}}/{{inputs.parameters.exec_code}}/regroup
                - name: threadNum
                  value: '10'
                - name: isCreateDir
                  value: '0'
                - name: xzqFile
                  value: '{{inputs.parameters.xzq_file}}'
            dependencies:
              - ogr2ogr-basic-quys
      outputs:
        parameters: []
        artifacts: []
    - name: delay
      inputs:
        parameters:
          - name: time
      suspend:
        duration: '{{inputs.parameters.time}}'
    - name: topo-1635322834720
      inputs:
        parameters:
          - name: input_file
          - name: output_file
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-gdal2tiles:v0.6.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: 
          - >-
            mkdir -p $(dirname {{inputs.parameters.output_file}});ogr2ogr
            {{inputs.parameters.output_file}} {{inputs.parameters.input_file}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
    - name: topo-1635329428266
      inputs:
        parameters:
          - name: dataSetId
          - name: dstPath
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: versionId
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-biz:v0.11.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 4Gi
            cpu: 4
          requests:
            memory: 4Gi
            cpu: 4
        args: 
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --dataSetId={{inputs.parameters.dataSetId}}
            --dstPath={{inputs.parameters.dstPath}}
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --versionId={{inputs.parameters.versionId}}
            --spring.config.location={{workflow.parameters.ceph_path}}/config/application-ai-{{workflow.parameters.env}}.yml
            --s3.protocol={{workflow.parameters.protocol}}
            --s3.ak={{workflow.parameters.accesskey}}
            --s3.sk={{workflow.parameters.secretkey}}
            --s3.bucket={{workflow.parameters.output_bucket}}
            --s3.endpoint={{workflow.parameters.endpoint}}
            --s3.lanEndpoint={{workflow.parameters.inner_endpoint}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
    - name: topo-1635329570107
      inputs:
        parameters:
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: inputFile
          - name: outputFile
          - name: operatorCodeAlias
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-compress:v0.9.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: 
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --inputFile={{inputs.parameters.inputFile}}
            --outputFile={{inputs.parameters.outputFile}}
            --operatorCodeAlias={{inputs.parameters.operatorCodeAlias}}
            --spring.config.location={{workflow.parameters.ceph_path}}/config/application-ai-{{workflow.parameters.env}}.yml
            --s3.protocol={{workflow.parameters.protocol}}
            --s3.ak={{workflow.parameters.accesskey}}
            --s3.sk={{workflow.parameters.secretkey}}
            --s3.bucket={{workflow.parameters.output_bucket}}
            --s3.endpoint={{workflow.parameters.endpoint}}
            --s3.lanEndpoint={{workflow.parameters.inner_endpoint}}
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
    - name: topo-1647571151413
      inputs:
        parameters:
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: obsDir
          - name: localPath
          - name: accessKey
          - name: secretKey
          - name: endpoint
          - name: protocol
          - name: bucket
          - name: operatorCodeAlias
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-compress:v0.9.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: 
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --obsDir={{inputs.parameters.obsDir}}
            --localPath={{inputs.parameters.localPath}}
            --accessKey={{inputs.parameters.accessKey}}
            --secretKey={{inputs.parameters.secretKey}}
            --endpoint={{inputs.parameters.endpoint}}
            --protocol={{inputs.parameters.protocol}}
            --bucket={{inputs.parameters.bucket}}
            --operatorCodeAlias={{inputs.parameters.operatorCodeAlias}}
            --spring.config.location={{workflow.parameters.ceph_path}}/config/application-ai-{{workflow.parameters.env}}.yml
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
    - name: topo-1652175963666
      inputs:
        parameters:
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: inputFile
          - name: xzqField
          - name: outputPath
          - name: threadNum
          - name: isCreateDir
          - name: xzqFile
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-gis-business:v0.7.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        resources:
          limits:
            memory: 8Gi
            cpu: 4
          requests:
            memory: 8Gi
            cpu: 4
        args: [' java -jar /opt/potato-algo-adapter.jar --tenantId={{inputs.parameters.tenantId}} --execCode={{inputs.parameters.execCode}} --operatorCode={{inputs.parameters.operatorCode}} --inputFile={{inputs.parameters.inputFile}} --xzqField={{inputs.parameters.xzqField}} --outputPath={{inputs.parameters.outputPath}} --threadNum={{inputs.parameters.threadNum}} --isCreateDir={{inputs.parameters.isCreateDir}} --xzqFile={{inputs.parameters.xzqFile}} --spring.config.location={{workflow.parameters.ceph_path}}/config/application-ai-{{workflow.parameters.env}}.yml --s3.protocol={{workflow.parameters.protocol}} --s3.ak={{workflow.parameters.accesskey}} --s3.sk={{workflow.parameters.secretkey}} --s3.bucket={{workflow.parameters.output_bucket}} --s3.endpoint={{workflow.parameters.endpoint}} --s3.lanEndpoint={{workflow.parameters.inner_endpoint}} ']
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
  volumes:
    - name: workdir
      hostPath:
        path: '{{workflow.parameters.ceph_path}}'
    - name: sharedir
      hostPath:
        path: '{{workflow.parameters.share_path}}'
