apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: mosaic-compress
  namespace: default
spec:
  entrypoint: mosaic-compress
  arguments:
    parameters:
      - name: ceph_path
        value: /mnt/cephfs
      - name: share_path
        value: /mnt/cifs
      - name: exec_code
        value: RSI202012345678
      - name: tenant_id
        value: 1
      - name: input_bucket
        value: rsi-private-beta
      - name: output_bucket
        value: rsi-operator
      - name: accesskey
        value: EY10QIYRK26F4CL0EY60
      - name: secretkey
        value: noYU7VQHMCojxX8ziuF04bAOMBUhKUKr79FcwyOQ
      - name: endpoint
        value: '10.4.1.110:7480'
      - name: inner_endpoint
        value: '10.4.1.110:7480'
      - name: protocol
        value: http
      - name: inner_protocol
        value: http
      - name: store_type
        value: 2
      - name: env
        value: beta5
      - name: input_path
        value: /mnt/cephfs/rsi/result/1/RSI202010101715/mosaic2tiles/
      - name: output_zip_file
        value: >-
          /mnt/cephfs/rsi/result/1/RSI202010101715/mosaic/RSI202010101715/RSI202010101715.zip
  onExit: ''
  templates:
    - name: mosaic-compress
      parallelism: 150
      inputs:
        parameters:
          - name: ceph_path
          - name: share_path
          - name: exec_code
          - name: tenant_id
          - name: input_bucket
          - name: output_bucket
          - name: accesskey
          - name: secretkey
          - name: endpoint
          - name: inner_endpoint
          - name: protocol
          - name: inner_protocol
          - name: store_type
          - name: env
          - name: input_path
          - name: output_zip_file
        artifacts: []
      dag:
        tasks:
          - name: compress-mvju
            template: topo-1622442211500
            key: topo-1622442211500
            arguments:
              parameters:
                - name: tenantId
                  value: '{{inputs.parameters.tenant_id}}'
                - name: execCode
                  value: '{{inputs.parameters.exec_code}}'
                - name: operatorCode
                  value: compress
                - name: inputFile
                  value: '{{inputs.parameters.input_path}}'
                - name: outputFile
                  value: '{{inputs.parameters.output_zip_file}}'
                - name: operatorCodeAlias
                  value: imageMosaic-compress
            dependencies: []
      outputs:
        parameters: []
        artifacts: []
    - name: delay
      inputs:
        parameters:
          - name: time
      suspend:
        duration: '{{inputs.parameters.time}}'
    - name: topo-1622442211500
      inputs:
        parameters:
          - name: tenantId
          - name: execCode
          - name: operatorCode
          - name: inputFile
          - name: outputFile
          - name: operatorCodeAlias
      container:
        image: 'registry.private.cloud:30002/rsi_group/rsi-compress:v0.9.0'
        command:
          - sh
          - '-c'
        imagePullPolicy: Always
        args:
          - >-
            java -jar /opt/potato-algo-adapter.jar
            --tenantId={{inputs.parameters.tenantId}}
            --execCode={{inputs.parameters.execCode}}
            --operatorCode={{inputs.parameters.operatorCode}}
            --inputFile={{inputs.parameters.inputFile}}
            --outputFile={{inputs.parameters.outputFile}}
            --operatorCodeAlias={{inputs.parameters.operatorCodeAlias}}
            --spring.config.location={{workflow.parameters.ceph_path}}/rsi/config/application-{{workflow.parameters.env}}.yml
            --s3.protocol={{workflow.parameters.protocol}}
            --s3.ak={{workflow.parameters.accesskey}}
            --s3.sk={{workflow.parameters.secretkey}}
            --s3.bucket={{workflow.parameters.output_bucket}}
            --s3.endpoint={{workflow.parameters.endpoint}}
            --s3.lanEndpoint={{workflow.parameters.inner_endpoint}}
        resources:
          limits:
            memory: 16Gi
            cpu: 8
          requests:
            memory: 16Gi
            cpu: 8
        volumeMounts:
          - name: workdir
            mountPath: '{{workflow.parameters.ceph_path}}'
          - name: sharedir
            mountPath: '{{workflow.parameters.share_path}}'
  hostNetwork: true
  volumes:
    - name: workdir
      hostPath:
        path: '{{workflow.parameters.ceph_path}}'
    - name: sharedir
      hostPath:
        path: '{{workflow.parameters.share_path}}'
